// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcBTJjMiKJR2SEAcZwB5VLcHfOxUXBpmY',
    appId: '1:10721053263:web:78d7a924dd6846a42ab83a',
    messagingSenderId: '10721053263',
    projectId: 'finance-tracker-9c4f4',
    authDomain: 'finance-tracker-9c4f4.firebaseapp.com',
    storageBucket: 'finance-tracker-9c4f4.firebasestorage.app',
    measurementId: 'G-Q7E4LRFWYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtUQSq0GPIuyk6tsDdS_yTTpqJUAy-lY8',
    appId: '1:10721053263:android:2a6f17cae3fb8cd02ab83a',
    messagingSenderId: '10721053263',
    projectId: 'finance-tracker-9c4f4',
    storageBucket: 'finance-tracker-9c4f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTigszVj-coKw2c-DvuhG93JPrlVJJSQk',
    appId: '1:10721053263:ios:59f61dfcc9db3a582ab83a',
    messagingSenderId: '10721053263',
    projectId: 'finance-tracker-9c4f4',
    storageBucket: 'finance-tracker-9c4f4.firebasestorage.app',
    androidClientId: '10721053263-02orfkkg2ph06jm23tu9dp758ukegmae.apps.googleusercontent.com',
    iosClientId: '10721053263-5j9qbsbd590lngeqr47bhmr9h8hihs6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.finance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTigszVj-coKw2c-DvuhG93JPrlVJJSQk',
    appId: '1:10721053263:ios:59f61dfcc9db3a582ab83a',
    messagingSenderId: '10721053263',
    projectId: 'finance-tracker-9c4f4',
    storageBucket: 'finance-tracker-9c4f4.firebasestorage.app',
    androidClientId: '10721053263-02orfkkg2ph06jm23tu9dp758ukegmae.apps.googleusercontent.com',
    iosClientId: '10721053263-5j9qbsbd590lngeqr47bhmr9h8hihs6m.apps.googleusercontent.com',
    iosBundleId: 'com.example.finance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcBTJjMiKJR2SEAcZwB5VLcHfOxUXBpmY',
    appId: '1:10721053263:web:14f6f68c89f9bb492ab83a',
    messagingSenderId: '10721053263',
    projectId: 'finance-tracker-9c4f4',
    authDomain: 'finance-tracker-9c4f4.firebaseapp.com',
    storageBucket: 'finance-tracker-9c4f4.firebasestorage.app',
    measurementId: 'G-52K5SC7W53',
  );

}